# Generated by Django 4.0 on 2022-01-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
