# Generated by Django 4.0 on 2022-01-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='115-1150152_default-profile-picture-avatar-png-green.jpg', null=True, upload_to='avatar'),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.myuser')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='accounts.myuser')),
            ],
        ),
    ]
