# Generated by Django 4.0 on 2022-01-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_avatar_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='user_from',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='user_to',
            new_name='to_user',
        ),
    ]
