# Generated by Django 4.0 on 2022-01-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_from_relation_from_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['-created']},
        ),
    ]
