# Generated by Django 4.0 on 2022-01-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_relation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
