# Generated by Django 4.0 on 2022-01-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_user_comment_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user',
        ),
    ]
